"""Add invoices table

Revision ID: 89974d66858b
Revises: 4cbd282d7d39
Create Date: 2024-08-07 13:33:57.468703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89974d66858b'
down_revision = '4cbd282d7d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
